name:                hs-wss-binance
version:             0.1.1.0
github:              "nikola-maric/hs-wss-binance"
license:             BSD3
author:              "Nikola Marić"
maintainer:          "nkl.maric@gmail.com"
copyright:           "2021 Nikola Maric"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nikola-maric/hs-wss-binance#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-local-signatures
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  dependencies:
    - wuss
    - websockets
    - text
    - bytestring
    - aeson
    - unagi-chan
    - network
    - world-peace
    - vector

tests:
  hs-wss-binance-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-wss-binance
