name:                hs-trader
version:             0.1.0.0
github:              "githubuser/hs-trader"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-trader#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-local-signatures
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  dependencies:
    - wuss
    - websockets
    - text
    - bytestring
    - aeson
    - deriving-aeson
    - unagi-chan
    - network
    - world-peace
    - unordered-containers

executables:
  hs-trader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wmissing-local-signatures
    - -Widentities
    - -Wredundant-constraints
    - -Wpartial-fields
    dependencies:
    - hs-trader
    - unagi-chan
    - async
    - world-peace

tests:
  hs-trader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-trader
